In [1]:
import numpy as np

In [2]:
L=[1,2,3,4,5,6,7]

In [49]:
A=np.array(L)

In [5]:
type(A)

numpy.ndarray

In [6]:
type(L)

list

In [16]:
A

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
A.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28])

In [17]:
A.sum()

28

In [18]:
A.min()

1

In [19]:
A.max()

7

In [20]:
A.mean()

4.0

In [21]:
A.prod()

5040

In [24]:
len(A)

7

In [76]:
A

In [68]:
A2=np.resize(A,8)

In [70]:
A2.put(7,8)

In [71]:
A2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
A=np.resize(A,8).put(7,8)

In [87]:
A3=np.array([[2,3,6],[4,6,8],[2,4,3]])

In [91]:
A=np.array(8)

In [92]:
A.ndim

0

In [115]:
A4=np.ones((2,100))

In [116]:
A4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [122]:
np.arange(-10,10,0.01)

array([-10.  ,  -9.99,  -9.98, ...,   9.97,   9.98,   9.99])