In [1]:
import  numpy as np


In [2]:
A=np.array([1,2,3,4,5,6,7])

In [6]:
A[1:4]

array([2, 3, 4])

In [8]:
A[-3:-1]

array([5, 6])

In [9]:
A1=list(range(1000))

In [11]:
A1=np.array(A1)

In [14]:
A1[-30:-10]

array([970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982,
       983, 984, 985, 986, 987, 988, 989])

In [18]:
A1[50:100:5]

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [21]:
A1[::10]

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510,
       520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640,
       650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770,
       780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900,
       910, 920, 930, 940, 950, 960, 970, 980, 990])

In [25]:
A2=np.array([A1,A1])

In [33]:
A2[0,1:4]

array([1, 2, 3])

In [38]:
A3=np.array([A1,A1*2])

In [46]:
A3[:,10:20]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])

In [47]:
A3=np.array([A1,A1*2,A1*5])

In [56]:
A3[:,10:50:5]

array([[ 10,  15,  20,  25,  30,  35,  40,  45],
       [ 20,  30,  40,  50,  60,  70,  80,  90],
       [ 50,  75, 100, 125, 150, 175, 200, 225]])

In [58]:
A4=np.array(['manzana','platano','piña'])

In [62]:
A5=np.array(['manzana','platano','piña',1,2,3,4.,5.,6.])

In [63]:
A5

array(['manzana', 'platano', 'piña', '1', '2', '3', '4.0', '5.0', '6.0'],
      dtype='<U32')

In [82]:
A6=A5[3:].astype('float')

In [77]:
A6**2

array([ 1.,  4.,  9., 16., 25., 36.])

In [81]:
A7=A5[3:].astype('float').copy()

In [87]:
A6.view()

array([1., 2., 3., 4., 5., 6.])

In [89]:
A7.view()

array([1., 2., 3., 4., 5., 6.])