In [1]:
import numpy as np

In [3]:
A=np.array([[2,34,4,5],[3,4,5,9]])

In [5]:
A.shape

(2, 4)

In [6]:
A.ndim

2

In [9]:
A2=np.array([1,2,3,4],ndmin=5)

In [11]:
A2.shape

(1, 1, 1, 1, 4)

In [12]:
A3=np.array(list(range(200)))

In [22]:
A4=A3.reshape(5,40)

In [23]:
A3.shape

(200,)

In [24]:
A4.shape

(5, 40)

In [25]:
A4.ndim

2

In [29]:
A5=np.array(list(range(12)))

In [30]:
A5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
A6=A5.reshape(2,3,2)

In [35]:
A6.shape

(2, 3, 2)

In [48]:
A7=A4.reshape(-1)

In [49]:
A8=A4.flatten()

In [50]:
A7==A8

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [53]:
for i in A4[0]:
    print('hola')

hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola


In [66]:
C=np.zeros((3,3))

In [67]:
for i in range(len(C)):
    for j in range(len(C[i])):
        C[(i,j)]=2**(j+i)
        


In [63]:
len(C)

3

In [68]:
C

array([[ 1.,  2.,  4.],
       [ 2.,  4.,  8.],
       [ 4.,  8., 16.]])

In [69]:
C0=np.zeros((3,3))

In [79]:
for x in np.nditer(C):
    for i in np.ndenumerate(C0):
        C0[i[0]]=x
    print(C0)
    
    

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]
[[16. 16. 16.]
 [16. 16. 16.]
 [16. 16. 16.]]


In [75]:
for i in np.ndenumerate(C0):
    print (i[0])

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)
(2, 0)
(2, 1)
(2, 2)


In [78]:
C0

array([[16., 16., 16.],
       [16., 16., 16.],
       [16., 16., 16.]])