In [1]:
from numpy import random as rnd

In [11]:
rnd.random()

0.2006052127185991

In [28]:
rnd.randint(15,50)+rnd.random()

27.816909207091786

In [32]:
rnd.randint(1,5,size=(100))

array([1, 4, 1, 2, 4, 2, 3, 4, 1, 2, 3, 4, 1, 3, 3, 3, 4, 3, 3, 4, 2, 3,
       4, 2, 3, 1, 1, 4, 4, 4, 1, 3, 2, 4, 1, 2, 3, 4, 2, 3, 4, 4, 2, 3,
       2, 3, 1, 2, 4, 2, 2, 4, 3, 4, 2, 3, 3, 3, 2, 4, 2, 4, 2, 1, 1, 4,
       4, 3, 3, 1, 1, 4, 1, 3, 2, 1, 2, 4, 4, 1, 2, 2, 3, 1, 2, 2, 3, 2,
       2, 4, 3, 1, 3, 1, 3, 3, 4, 3, 4, 3])

In [35]:
rnd.randint(1,5,size=(10,10))

array([[4, 2, 2, 3, 4, 4, 1, 2, 1, 1],
       [2, 3, 1, 4, 4, 1, 4, 4, 2, 1],
       [1, 3, 1, 3, 1, 2, 1, 3, 3, 4],
       [4, 1, 2, 3, 2, 3, 1, 4, 1, 2],
       [4, 4, 3, 1, 4, 1, 3, 1, 3, 4],
       [4, 2, 4, 3, 2, 4, 3, 4, 1, 2],
       [1, 3, 3, 1, 4, 4, 3, 4, 1, 1],
       [2, 2, 1, 4, 2, 4, 4, 4, 4, 1],
       [1, 4, 3, 4, 4, 1, 1, 2, 4, 1],
       [1, 1, 1, 4, 4, 2, 4, 2, 2, 1]])

In [43]:
rnd.randint(1,5,size=(100,2))+rnd.random((100,2))

array([[3.66357302, 1.77944808],
       [4.0347805 , 1.49565429],
       [4.56770419, 4.92927757],
       [3.40227588, 1.54261762],
       [2.21589261, 1.08001324],
       [2.36653382, 2.57485098],
       [3.0984674 , 2.72150166],
       [1.9124883 , 1.72272344],
       [2.97529445, 3.86638149],
       [3.61239818, 4.93975526],
       [3.92969533, 1.32813921],
       [4.08957333, 4.91303544],
       [1.29179926, 1.3858377 ],
       [1.33239549, 1.14941609],
       [1.17295155, 4.27396049],
       [2.25990422, 4.43528597],
       [3.97326895, 1.87704694],
       [3.49970959, 1.87246215],
       [2.94279167, 1.50170614],
       [3.7859645 , 3.23515103],
       [2.49525656, 2.73610815],
       [2.83707459, 1.01848914],
       [2.50429178, 1.03705099],
       [3.56920633, 3.00170635],
       [3.03792115, 3.61225212],
       [2.19870313, 3.61804148],
       [3.66371732, 1.02711167],
       [2.37146478, 3.09548891],
       [4.30003176, 4.61124652],
       [1.7819683 , 1.71849312],
       [1.

In [45]:
L=list(range(1000))

In [46]:
L

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [51]:
rnd.choice(L)

471

In [52]:
L2=['Luis','Rosa','Lili','Pedro']

In [55]:
rnd.choice(L2)

'Rosa'

In [57]:
D=(list(range(1,21)))

In [63]:
def tiro():
    return rnd.choice(D)

In [66]:
tiro()

16

In [72]:
rnd.choice(D,size=(100,3))

array([[ 4,  4,  5],
       [16, 13, 12],
       [ 1, 19, 13],
       [15,  1,  3],
       [20, 20, 16],
       [ 9,  4, 17],
       [20,  7,  6],
       [18, 14,  5],
       [ 7, 16,  1],
       [16, 13, 10],
       [ 9, 15, 19],
       [19,  9,  5],
       [ 1, 11, 20],
       [10,  2,  1],
       [17, 11,  2],
       [10, 12,  9],
       [ 4,  7, 17],
       [ 5, 14, 20],
       [17,  2,  8],
       [10,  5, 18],
       [15, 12,  1],
       [15, 20,  6],
       [ 2,  9, 15],
       [18,  4, 13],
       [ 9, 19,  3],
       [ 6,  6, 10],
       [ 5,  5,  8],
       [19,  1, 16],
       [ 6, 17,  4],
       [ 3,  9, 12],
       [ 7, 19,  9],
       [18, 18,  3],
       [ 3, 14,  4],
       [16, 12,  5],
       [12,  3,  8],
       [20, 19, 11],
       [11, 19,  8],
       [ 7, 15, 12],
       [ 7,  3, 13],
       [ 5, 15,  2],
       [18,  3, 14],
       [15,  8,  8],
       [ 6, 10,  8],
       [13, 15, 19],
       [ 7,  9, 15],
       [15,  8,  2],
       [17, 14,  5],
       [19,  

In [88]:
rnd.choice(['S','L','N'],p=[0.65,0.25,0.10],size=(100,10))

array([['S', 'N', 'L', 'S', 'S', 'S', 'S', 'S', 'L', 'L'],
       ['S', 'L', 'S', 'N', 'S', 'N', 'L', 'S', 'S', 'S'],
       ['S', 'S', 'S', 'S', 'L', 'S', 'S', 'S', 'S', 'L'],
       ['S', 'S', 'S', 'L', 'S', 'S', 'L', 'S', 'S', 'L'],
       ['S', 'N', 'S', 'S', 'S', 'N', 'S', 'S', 'S', 'S'],
       ['S', 'S', 'S', 'L', 'L', 'S', 'S', 'S', 'S', 'S'],
       ['L', 'S', 'S', 'S', 'S', 'S', 'L', 'S', 'S', 'N'],
       ['L', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
       ['L', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'N', 'S'],
       ['N', 'L', 'L', 'S', 'L', 'S', 'S', 'S', 'N', 'L'],
       ['L', 'S', 'S', 'S', 'S', 'L', 'S', 'L', 'S', 'S'],
       ['L', 'L', 'S', 'S', 'S', 'N', 'N', 'S', 'N', 'S'],
       ['S', 'S', 'N', 'S', 'S', 'S', 'S', 'S', 'S', 'L'],
       ['S', 'S', 'S', 'N', 'N', 'S', 'S', 'L', 'S', 'S'],
       ['L', 'S', 'S', 'L', 'S', 'S', 'S', 'N', 'N', 'S'],
       ['S', 'S', 'N', 'L', 'S', 'L', 'L', 'S', 'S', 'N'],
       ['L', 'L', 'S', 'L', 'S', 'N', 'L', 'S', 'L', 'S'

In [92]:
A=rnd.random((10,10))


In [94]:
A

array([[0.42539386, 0.69078398, 0.5923747 , 0.18081442, 0.01920004,
        0.00133775, 0.21618621, 0.27313686, 0.03467393, 0.62150538],
       [0.65468441, 0.188334  , 0.83513658, 0.81265522, 0.35823073,
        0.80963236, 0.35093944, 0.6039069 , 0.28656847, 0.40679159],
       [0.92307675, 0.74960292, 0.57682912, 0.8268101 , 0.96966188,
        0.57574895, 0.48754532, 0.86016796, 0.02554879, 0.38003951],
       [0.68388639, 0.40259377, 0.94690503, 0.9297607 , 0.84809288,
        0.11494405, 0.36734626, 0.50189435, 0.99814379, 0.40128871],
       [0.27324471, 0.31482236, 0.38601802, 0.85866404, 0.94789979,
        0.15949112, 0.70322508, 0.39259804, 0.89998802, 0.65312615],
       [0.11713636, 0.48132444, 0.06145813, 0.78364544, 0.55617327,
        0.51244913, 0.32592918, 0.93343359, 0.99604633, 0.12445334],
       [0.82634912, 0.89159116, 0.95356634, 0.04340612, 0.18933636,
        0.62610279, 0.46191597, 0.41874516, 0.20657493, 0.15558476],
       [0.28424806, 0.66668905, 0.3439096

In [96]:
rnd.shuffle(A)

In [103]:
import numpy as np
x=np.arange(0,1.01,0.01)

In [104]:
x

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [105]:
rnd.shuffle(x)

In [106]:
x

array([0.68, 0.91, 0.44, 0.03, 0.64, 0.09, 0.41, 0.75, 0.81, 0.46, 0.12,
       0.84, 0.3 , 0.82, 0.88, 0.69, 0.47, 0.59, 0.4 , 0.74, 0.42, 0.27,
       0.33, 0.96, 0.51, 0.55, 0.8 , 0.08, 0.35, 0.53, 0.57, 0.9 , 0.86,
       0.87, 0.97, 0.43, 0.  , 0.24, 0.06, 0.22, 0.79, 0.62, 0.32, 0.39,
       0.11, 0.1 , 0.15, 1.  , 0.49, 0.99, 0.98, 0.05, 0.26, 0.04, 0.5 ,
       0.61, 0.07, 0.18, 0.34, 0.95, 0.93, 0.2 , 0.58, 0.01, 0.38, 0.63,
       0.13, 0.76, 0.52, 0.16, 0.73, 0.7 , 0.66, 0.83, 0.14, 0.78, 0.6 ,
       0.23, 0.37, 0.65, 0.17, 0.72, 0.28, 0.54, 0.94, 0.45, 0.92, 0.56,
       0.89, 0.31, 0.25, 0.77, 0.85, 0.29, 0.02, 0.19, 0.71, 0.36, 0.67,
       0.48, 0.21])

In [114]:
rnd.permutation(x)

array([0.47, 0.91, 0.76, 0.63, 0.45, 0.08, 0.56, 0.65, 0.15, 0.39, 0.07,
       0.52, 0.19, 0.33, 0.2 , 0.79, 0.1 , 0.64, 0.53, 0.35, 0.12, 0.  ,
       0.83, 0.68, 0.77, 0.96, 0.13, 0.87, 0.9 , 0.89, 0.21, 0.78, 0.25,
       0.81, 0.5 , 0.48, 0.23, 0.88, 0.7 , 0.18, 0.98, 0.74, 0.67, 0.8 ,
       0.84, 0.42, 0.22, 0.75, 0.3 , 0.97, 0.17, 0.58, 0.92, 0.03, 0.44,
       0.31, 0.05, 0.11, 0.16, 0.85, 0.26, 0.99, 0.34, 0.49, 0.01, 0.38,
       0.61, 0.93, 0.55, 0.86, 0.43, 0.4 , 0.94, 0.24, 0.57, 0.73, 0.59,
       0.14, 0.29, 0.32, 0.62, 0.6 , 0.02, 0.82, 0.51, 0.41, 0.28, 0.72,
       0.09, 0.71, 0.36, 0.46, 0.69, 0.37, 0.95, 0.66, 0.54, 1.  , 0.06,
       0.27, 0.04])

In [120]:
rnd.normal(loc=0,scale=0.5,size=(100))

array([ 0.06527256,  0.84608218, -0.26837355, -0.61988318, -0.26318551,
       -0.70113837,  0.42020461, -0.04588355, -0.25524255, -0.57381081,
       -0.24953266,  0.12001119, -1.41063837,  0.02189651, -0.06682483,
       -0.01051654,  0.94821741, -0.62218487,  0.38923042,  0.02741227,
       -0.31600599, -0.44074896,  0.25748341,  0.86875065, -0.07494038,
        0.89621364,  0.72959127, -0.13608385, -0.44466472,  0.06965898,
        1.61396467, -0.06001439,  0.16845124, -0.75583106,  0.33748687,
       -0.21663912, -0.26763405, -0.04426015, -0.90169368, -0.49200956,
        0.27841746, -0.30019269, -0.56498053,  0.34267592,  0.29579164,
       -0.31735855,  1.75877827, -0.32802775,  0.15448437,  0.50824379,
        0.75080016, -0.06530316,  0.25671518,  0.39682876, -0.16048974,
        0.47633994, -0.41767821,  0.03369621, -0.18253942, -0.45540295,
       -0.42974237,  0.3449461 ,  0.63410938,  0.16374473, -0.78926852,
        0.28131759,  0.07251991, -0.19970431, -0.12061715, -0.43

In [124]:
rnd.binomial(n=1000,p=0.5,size=(10000))

array([492, 491, 496, ..., 509, 486, 493])

In [128]:
rnd.poisson(lam=10,size=(1000))

array([12, 10,  6, 10, 10, 13, 10,  7, 11, 10,  6,  9,  9,  6,  5,  6,  9,
        8,  7, 10,  6, 11,  4, 16, 10,  9,  9, 10, 10, 10,  6, 10, 13, 12,
       12,  9, 11, 12,  9, 11, 12, 16, 12, 11, 13, 18, 10,  4,  8, 17,  9,
        8, 10, 14, 10, 15, 12,  9,  7, 11, 13,  8,  7, 19, 19, 12, 14,  5,
       10, 11, 11, 11, 12,  6, 11, 13, 10, 10,  9, 11, 10, 11,  7,  4, 13,
        7, 11,  4,  9, 12,  7, 11,  9, 11, 10,  8,  7,  8,  6,  3,  9, 11,
       12, 10,  8,  7, 11, 10, 14, 11, 12,  7, 11, 16, 11, 12,  5, 12, 13,
       10,  8, 11,  7, 11, 13,  8, 10,  8, 11,  9,  9, 10,  8, 14, 11,  9,
       12, 12, 11, 14,  3, 11,  5, 14, 10,  8, 15, 16,  4,  8, 10,  8, 11,
        9,  8,  7, 15, 12, 10, 10,  7, 14, 10, 10,  9, 13, 13, 14, 10, 10,
       11, 20,  5, 16,  9, 12, 12, 10, 10,  8, 12, 10, 12, 10,  4, 11,  7,
        8,  8,  7,  7,  9,  9,  3,  9, 13,  9,  9,  4,  7,  6, 10,  7,  9,
        7, 14, 10, 11, 10, 13,  8,  7,  8, 12, 12, 15,  5, 14,  9,  9,  9,
       12,  7,  5,  4, 12

In [133]:
rnd.uniform(110,size=(100))

array([ 88.92145051,  71.92860508,  74.70918984,  21.21738072,
        65.85528266,  54.43986911, 100.15024771,  54.21656936,
       109.06419887,  59.28176484,  86.51756774,  72.80178687,
        84.14008095,  18.24852031,  44.23298839,  93.77452692,
        13.39667878,  30.89643768, 108.56898569,  74.6915695 ,
        97.14469534,  35.23521182, 102.97441931,  64.66316775,
        29.5003941 ,  47.89522757,  85.59392528,  19.69957734,
        89.62068083,  83.86532289,  23.82846874,  83.77836138,
        21.96356657,  68.05850914,  46.67498151, 102.27752068,
        92.55443333,  46.32740354,  59.22962253,  25.06420648,
        42.20208244,  30.63173538,  17.26323431,   2.60085352,
        84.48273596,  52.76593145,  36.67026659,  35.11326515,
        29.85763525,  41.75560527,  12.94144928,   6.49916406,
       107.76713406,  56.46607638,  85.22581138,  40.14647425,
        41.0859611 ,   7.00815528,  29.17854092,   7.60740633,
        93.95445884,  48.06618758,  13.54267433,   7.38

In [134]:
rnd.logistic(loc=1,scale=2,size=100)

array([-1.04975404, -1.54242754,  7.07265351,  2.85432513, -0.67295348,
        4.71336634,  2.9949617 , -2.76414172,  6.45675995,  3.92295742,
       -4.56325919, -2.37167245,  8.47841697,  8.89863734,  0.85355209,
       -2.88092042,  7.40498629,  7.71827109,  3.94449359,  6.06274774,
       -3.69490611,  3.24057558, -0.25985535, -0.67777712,  6.31039128,
        3.70815765,  2.4271411 , -4.69563894,  1.74195194,  1.50834181,
        9.57264483,  0.25310362,  0.91512794,  3.22046564,  2.22150613,
        2.97984889, -2.38021877, -0.85778879, -1.52586901, -0.41840429,
        7.74474509,  2.38031049, -2.58247056,  0.03560755,  8.10006763,
        7.82487774,  1.13277   , -2.81336057, -0.56193644,  3.77471926,
        3.79411338, -5.45726199,  6.84115805, -2.01928823,  3.09271668,
        2.86508277, -0.04723506, -0.78036452, -1.54045511,  5.45461465,
        0.59779386, -2.15818554,  4.34261588,  1.65520008,  1.46967766,
        8.12285188, -0.88178142, -3.54867004,  2.1982318 ,  2.41

In [139]:
rnd.exponential(scale=0.1,size=100)

array([8.35701493e-02, 1.97203928e-02, 1.14665238e-02, 5.69615434e-02,
       1.58634554e-01, 9.76773832e-03, 1.04193546e-01, 2.19498673e-02,
       6.27840423e-02, 4.40638869e-03, 1.07789050e-01, 4.97952712e-02,
       2.09765570e-03, 1.48571141e-01, 3.44363355e-03, 1.55769015e-04,
       5.08259390e-02, 2.08065549e-02, 1.97634787e-02, 2.14842949e-02,
       2.15959053e-01, 4.47409312e-02, 1.36336343e-01, 3.32102846e-01,
       3.88014902e-01, 2.27829268e-02, 8.57826991e-02, 5.61294242e-02,
       6.78047288e-02, 8.02989574e-03, 4.66607414e-02, 6.24548921e-03,
       3.55561516e-02, 9.10791307e-02, 8.38031920e-02, 6.75772719e-02,
       4.20536028e-02, 3.96155774e-01, 4.98464785e-02, 8.09606616e-02,
       2.83924248e-02, 1.07390509e-02, 2.45671495e-02, 2.18078167e-01,
       6.87077013e-02, 3.26723399e-01, 7.84074671e-02, 1.99832367e-01,
       1.08851172e-01, 1.69442749e-02, 1.15087702e-01, 3.81923229e-02,
       1.41928140e-02, 6.68629373e-02, 6.97040731e-02, 1.56711071e-01,
      